Repository London-Squad/PlanMate, pull requests merged in 2025-05, with the labels that each got.

#62 Feature/refactor TaskManagementView and add task logs
  src/main/kotlin/data/CsvTasksDataSource.kt
  src/main/kotlin/data/LogsDataSource.kt
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/logic/exceptions/exceptions.kt
  src/main/kotlin/logic/repositories/TaskRepository.kt
  src/main/kotlin/logic/useCases/ManageTaskUseCase.kt
  src/main/kotlin/ui/projectView/ProjectTasksView.kt
  src/main/kotlin/ui/taskManagementView/TaskDeletionView.kt
  src/main/kotlin/ui/taskManagementView/TaskDescriptionEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskManagementView.kt
  src/main/kotlin/ui/taskManagementView/TaskStateEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskTitleEditionView.kt
Labels: finished

#65 feature/separate input validation from reader class
  src/main/kotlin/di/logicModule.kt
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/logic/validation/UserInputValidator.kt
  src/main/kotlin/ui/cliPrintersAndReaders/CLIPrinter.kt
  src/main/kotlin/ui/cliPrintersAndReaders/CLIReader.kt
  src/main/kotlin/ui/mainMenuView/MainMenuView.kt
  src/main/kotlin/ui/matesManagementView/MateCreationView.kt
  src/main/kotlin/ui/matesManagementView/MatesManagementView.kt
  src/main/kotlin/ui/projectView/EditProjectView.kt
  src/main/kotlin/ui/projectView/ProjectTasksView.kt
  src/main/kotlin/ui/projectView/ProjectView.kt
  src/main/kotlin/ui/projectsView/ProjectsView.kt
  src/main/kotlin/ui/statesView/StatesView.kt
  src/main/kotlin/ui/taskManagementView/TaskDeletionView.kt
  src/main/kotlin/ui/taskManagementView/TaskDescriptionEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskManagementView.kt
  src/main/kotlin/ui/taskManagementView/TaskStateEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskTitleEditionView.kt
  src/main/kotlin/ui/welcomeView/WelcomeView.kt
Labels: finished

#67 Refactor/move cache data source into authentication repo
  src/main/kotlin/data/AuthenticationDataSource.kt
  src/main/kotlin/data/CacheDataSource.kt
  src/main/kotlin/di/dataModule.kt
  src/main/kotlin/di/logicModule.kt
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/logic/repositories/AuthenticationRepository.kt
  src/main/kotlin/logic/repositories/CacheDataRepository.kt
  src/main/kotlin/logic/useCases/ClearLoggedInUserFromCacheUseCase.kt
  src/main/kotlin/logic/useCases/CreateMateUseCase.kt
  src/main/kotlin/logic/useCases/GetLoggedInUserUseCase.kt
  src/main/kotlin/logic/useCases/LoginUseCase.kt
  src/main/kotlin/logic/useCases/LogoutUseCase.kt
  src/main/kotlin/logic/useCases/ManageStateUseCase.kt
  src/main/kotlin/logic/useCases/ManageTaskUseCase.kt
  src/main/kotlin/logic/useCases/ProjectUseCases.kt
  src/main/kotlin/ui/loginView/LoginView.kt
  src/main/kotlin/ui/mainMenuView/MainMenuView.kt
  src/main/kotlin/ui/matesManagementView/MateCreationView.kt
  src/main/kotlin/ui/projectView/ProjectView.kt
  src/main/kotlin/ui/projectsView/ProjectsView.kt
  src/main/kotlin/ui/taskManagementView/TaskStateEditionView.kt
  src/test/kotlin/data/repository/AuthenticationDataSourceTest.kt
  src/test/kotlin/logic/useCases/ChangePasswordUseCaseTest.kt
  src/test/kotlin/logic/useCases/GetLoggedInUserUseCaseTest.kt
  src/test/kotlin/logic/useCases/LoginUseCaseTest.kt
  src/test/kotlin/logic/useCases/LogoutUseCaseTest.kt
  src/test/kotlin/logic/useCases/ManageStateUseCaseTest.kt
  src/test/kotlin/logic/useCases/SignupUseCaseTest.kt
  src/test/kotlin/ui/mainMenuView/MainMenuViewTest.kt
  src/test/kotlin/ui/matesManagementView/MateCreationViewTest.kt
  src/test/kotlin/ui/matesManagementView/MatesManagementViewTest.kt
  src/test/kotlin/ui/projectView/ProjectTasksViewTest.kt
  src/test/kotlin/ui/projectView/ProjectViewTest.kt
  src/test/kotlin/ui/projectsView/ProjectsViewTest.kt
Labels: finished

#73 feature/add confirm before delete project
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/ui/cliPrintersAndReaders/CLIReader.kt
  src/main/kotlin/ui/projectView/DeleteProjectView.kt
Labels: finished

#77 Feature/add mongoDB dependency and dataSource structure
  .gitignore
  build.gradle.kts
  src/main/kotlin/data/entitiesData/LogData.kt
  src/main/kotlin/data/entitiesData/ProjectData.kt
  src/main/kotlin/data/entitiesData/TaskData.kt
  src/main/kotlin/data/entitiesData/TaskStateData.kt
  src/main/kotlin/data/entitiesData/UserData.kt
  src/main/kotlin/data/mongoDBDataSource/DataBaseConnection.kt
  src/main/kotlin/data/mongoDBDataSource/MongoDBAuthenticationDataSource.kt
  src/main/kotlin/data/mongoDBDataSource/MongoDBLogsDataSource.kt
  src/main/kotlin/data/mongoDBDataSource/MongoDBProjectsDataSource.kt
  src/main/kotlin/data/mongoDBDataSource/MongoDBTaskStatesDataSource.kt
  src/main/kotlin/data/mongoDBDataSource/MongoDBTasksDataSource.kt
Labels: finished

#85 Refactor/table UI
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/ui/cliPrintersAndReaders/cliTable/CLITablePrinter.kt
  src/main/kotlin/ui/cliPrintersAndReaders/cliTable/TablePrinterExceptions.kt
  src/main/kotlin/ui/logsView/LogsView.kt
  src/main/kotlin/ui/projectDetailsView/SwimlanesView.kt
  src/main/kotlin/ui/projectsDashboardView/ProjectsDashboardView.kt
  src/test/kotlin/ui/projectsDashboardView/ProjectsDashboardViewTest.kt
Labels: finished

#93 Refactor StatesView to Use Index-Based State Selection and Enhance Input Validation
  src/main/kotlin/data/mongoDBDataSource/MongoDBProjectsDataSource.kt
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/ui/projectDetailsView/EditProjectView.kt
  src/main/kotlin/ui/statesView/StatesView.kt
  src/main/kotlin/ui/tasksStatesView/TasksStatesView.kt
  src/test/kotlin/ui/projectDetailsView/EditProjectDetailsViewTest.kt
  src/test/kotlin/ui/tasksStatesView/StatesViewTest.kt
Labels: finished

#114 refactore/separate entity validators
  src/main/kotlin/di/csvStorage.kt
  src/main/kotlin/di/logicModule.kt
  src/main/kotlin/di/mongoStorageModule.kt
  src/main/kotlin/di/uiModule.kt
  src/main/kotlin/logic/validation/ProjectInputValidator.kt
  src/main/kotlin/logic/validation/TaskInputValidator.kt
  src/main/kotlin/logic/validation/TaskStateInputValidator.kt
  src/main/kotlin/logic/validation/UserInputValidator.kt
  src/main/kotlin/ui/cliPrintersAndReaders/CLIReader.kt
  src/main/kotlin/ui/cliPrintersAndReaders/ProjectInputReader.kt
  src/main/kotlin/ui/cliPrintersAndReaders/TaskInputReader.kt
  src/main/kotlin/ui/cliPrintersAndReaders/TaskStateInputReader.kt
  src/main/kotlin/ui/mainMenuView/MainMenuView.kt
  src/main/kotlin/ui/matesManagementView/MatesManagementView.kt
  src/main/kotlin/ui/projectDetailsView/EditProjectView.kt
  src/main/kotlin/ui/projectDetailsView/ProjectDetailsView.kt
  src/main/kotlin/ui/projectsDashboardView/ProjectsDashboardView.kt
  src/main/kotlin/ui/taskManagementView/TaskDescriptionEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskManagementView.kt
  src/main/kotlin/ui/taskManagementView/TaskStateEditionView.kt
  src/main/kotlin/ui/taskManagementView/TaskTitleEditionView.kt
  src/main/kotlin/ui/tasksStatesView/TasksStatesView.kt
  src/main/kotlin/ui/welcomeView/WelcomeView.kt
Labels: finished

#117 rename Action classes to more descriptive names
  src/main/kotlin/data/csvDataSource/dtoMappers/LogMapper.kt
  src/main/kotlin/data/repositoriesImpl/LogsRepositoryImpl.kt
  src/main/kotlin/logic/entities/Action.kt
  src/main/kotlin/logic/entities/Log.kt
  src/main/kotlin/logic/entities/LoggedAction.kt
  src/main/kotlin/logic/useCases/ManageStateUseCase.kt
  src/main/kotlin/logic/useCases/ManageTaskUseCase.kt
  src/main/kotlin/logic/useCases/ProjectUseCases.kt
  src/main/kotlin/ui/logsView/LogsView.kt
Labels: finished

#122 refactor: split AuthenticationRepository into AuthenticationRepositor…
  src/main/kotlin/data/repositories/AuthenticationRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/di/dataModule.kt
  src/main/kotlin/logic/repositories/AuthenticationRepository.kt
  src/main/kotlin/logic/repositories/UserRepository.kt
  src/main/kotlin/logic/useCases/mateUseCase/CreateMateUseCase.kt
  src/main/kotlin/logic/useCases/mateUseCase/GetAllMatesUseCase.kt
Labels: finished

#132 Handle exception that happen at data layer and logic
  src/main/kotlin/data/dataSources/csvDataSource/fileIO/CsvFileHandler.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBLogsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBProjectsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTaskStatesDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTasksDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBUsersDataSource.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/logic/exceptions/exceptions.kt
  src/main/kotlin/logic/validation/CredentialValidator.kt
  src/test/kotlin/logic/useCases/LoginUseCaseTest.kt
Labels: finished

#151 Refactor/remove unnecessary repositories
  src/main/kotlin/data/dataSources/csvDataSource/CsvLoggedInUserCacheDataSource.kt
  src/main/kotlin/data/dataSources/csvDataSource/CsvLogsDataSource.kt
  src/main/kotlin/data/dataSources/csvDataSource/CsvProjectsDataSource.kt
  src/main/kotlin/data/dataSources/csvDataSource/CsvTaskStatesDataSource.kt
  src/main/kotlin/data/dataSources/csvDataSource/CsvTasksDataSource.kt
  src/main/kotlin/data/dataSources/csvDataSource/CsvUsersDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBLogsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBProjectsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTaskStatesDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTasksDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBUsersDataSource.kt
  src/main/kotlin/data/repositories/AuthenticationRepositoryImpl.kt
  src/main/kotlin/data/repositories/LogsRepositoryImpl.kt
  src/main/kotlin/data/repositories/ProjectsRepositoryImpl.kt
  src/main/kotlin/data/repositories/TaskStatesRepositoryImpl.kt
  src/main/kotlin/data/repositories/TasksRepositoryImpl.kt
  src/main/kotlin/data/repositories/UserRepositoryImpl.kt
  src/main/kotlin/data/repositories/dataSourceInterfaces/LogsDataSource.kt
  src/main/kotlin/data/repositories/dataSourceInterfaces/ProjectsDataSource.kt
  src/main/kotlin/data/repositories/dataSourceInterfaces/TaskStatesDataSource.kt
  src/main/kotlin/data/repositories/dataSourceInterfaces/TasksDataSource.kt
  src/main/kotlin/data/repositories/dataSources/LoggedInUserCacheDataSource.kt
  src/main/kotlin/data/repositories/dataSources/UsersDataSource.kt
  src/main/kotlin/data/repositories/dtoMappers/LogMapper.kt
  src/main/kotlin/di/csvStorage.kt
  src/main/kotlin/di/dataModule.kt
  src/main/kotlin/di/mongoStorageModule.kt
  src/main/kotlin/logic/exceptions/exceptions.kt
  src/main/kotlin/logic/repositories/AuthenticationRepository.kt
  src/main/kotlin/logic/repositories/TaskRepository.kt
  src/main/kotlin/logic/repositories/TaskStatesRepository.kt
  src/main/kotlin/logic/useCases/GetLoggedInUserUseCase.kt
  src/main/kotlin/logic/useCases/ManageTaskUseCase.kt
  src/main/kotlin/logic/validation/CredentialValidator.kt
  src/main/kotlin/ui/RequestHandler.kt
  src/test/kotlin/ui/matesManagementView/MateCreationViewTest.kt
Labels: In progress

#127 make test for some classes in the ui and the useCase
  build.gradle.kts
  src/test/kotlin/fakeData.kt
  src/test/kotlin/logic/useCases/CreateMateUseCaseTest.kt
  src/test/kotlin/logic/useCases/GetLoggedInUserUseCaseTest.kt
  src/test/kotlin/logic/useCases/LoginUseCaseTest.kt
  src/test/kotlin/logic/useCases/LogoutUseCaseTest.kt
  src/test/kotlin/ui/loginView/LoginViewTest.kt
  src/test/kotlin/ui/mainMenuView/MainMenuViewTest.kt
  src/test/kotlin/ui/welcomeView/WelcomeViewTest.kt
Labels: suspended

#159 Refactor/mongodb query handler
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBLogsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBProjectsDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTaskStatesDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBTasksDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBUsersDataSource.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/mongoDBHandler/MongoDBParser.kt
  src/main/kotlin/data/dataSources/mongoDBDataSource/mongoDBHandler/MongoDBQueryHandler.kt
  src/main/kotlin/di/mongoStorageModule.kt
  src/main/kotlin/ui/projectDetailsView/ProjectDetailsView.kt
  src/main/kotlin/ui/projectsDashboardView/ProjectsDashboardView.kt
Labels: finished
